version: "3.9"

services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
      target: dev
    image: api:0.10.0
    ports:
      - 3001:3000
    depends_on:
      - postgres
      - redis
  postgres:
    image: postgres:latest
    container_name: clinic-postgres
    ports:
      - 5432:5432
    restart: always
    env_file:
      - ./api/.env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres:/var/lib/postgresql/data
  redis:
    image: redis:latest
    container_name: clinic-redis
    ports:
      - 6379:6379
    volumes:
      - redis:/data
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    image: client:0.0.1
    ports:
      - 3000:3000
volumes:
  postgres:
  redis:
